package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import nc.o2;
import nc.q3;
import nc.s3;

/* compiled from: r8-map-id-d9727bc7e00235ac513a61fce9aaf2b7a3ad41c0941d80eeaba89f3cd6d3eec5 */
/* loaded from: classes.dex */
public final class zzbuu extends od.a {
    public static final Parcelable.Creator<zzbuu> CREATOR = new zzbuv();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final o2 zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbmn zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final q3 zzc;
    public final s3 zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final rc.a zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbgc zzy;
    public final List zzz;

    public zzbuu(int i10, Bundle bundle, q3 q3Var, s3 s3Var, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, rc.a aVar, Bundle bundle2, int i11, List list, Bundle bundle3, boolean z2, int i12, int i13, float f10, String str5, long j, String str6, List list2, String str7, zzbgc zzbgcVar, List list3, long j4, String str8, float f11, boolean z10, int i14, int i15, boolean z11, String str9, String str10, boolean z12, int i16, Bundle bundle4, String str11, o2 o2Var, boolean z13, Bundle bundle5, String str12, String str13, String str14, boolean z14, List list4, String str15, List list5, int i17, boolean z15, boolean z16, boolean z17, ArrayList arrayList, String str16, zzbmn zzbmnVar, String str17, Bundle bundle6) {
        this.zza = i10;
        this.zzb = bundle;
        this.zzc = q3Var;
        this.zzd = s3Var;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = aVar;
        this.zzl = bundle2;
        this.zzm = i11;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z2;
        this.zzq = i12;
        this.zzr = i13;
        this.zzs = f10;
        this.zzt = str5;
        this.zzu = j;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbgcVar;
        this.zzA = j4;
        this.zzB = str8;
        this.zzC = f11;
        this.zzH = z10;
        this.zzD = i14;
        this.zzE = i15;
        this.zzF = z11;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z12;
        this.zzK = i16;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = o2Var;
        this.zzO = z13;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z14;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i17;
        this.zzY = z15;
        this.zzZ = z16;
        this.zzaa = z17;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzbmnVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i10) {
        int i11 = this.zza;
        int iH0 = uk.c.h0(20293, parcel);
        uk.c.k0(parcel, 1, 4);
        parcel.writeInt(i11);
        uk.c.U(parcel, 2, this.zzb, false);
        uk.c.b0(parcel, 3, this.zzc, i10, false);
        uk.c.b0(parcel, 4, this.zzd, i10, false);
        uk.c.c0(parcel, 5, this.zze, false);
        uk.c.b0(parcel, 6, this.zzf, i10, false);
        uk.c.b0(parcel, 7, this.zzg, i10, false);
        uk.c.c0(parcel, 8, this.zzh, false);
        uk.c.c0(parcel, 9, this.zzi, false);
        uk.c.c0(parcel, 10, this.zzj, false);
        uk.c.b0(parcel, 11, this.zzk, i10, false);
        uk.c.U(parcel, 12, this.zzl, false);
        int i12 = this.zzm;
        uk.c.k0(parcel, 13, 4);
        parcel.writeInt(i12);
        uk.c.e0(parcel, 14, this.zzn);
        uk.c.U(parcel, 15, this.zzo, false);
        boolean z2 = this.zzp;
        uk.c.k0(parcel, 16, 4);
        parcel.writeInt(z2 ? 1 : 0);
        int i13 = this.zzq;
        uk.c.k0(parcel, 18, 4);
        parcel.writeInt(i13);
        int i14 = this.zzr;
        uk.c.k0(parcel, 19, 4);
        parcel.writeInt(i14);
        float f10 = this.zzs;
        uk.c.k0(parcel, 20, 4);
        parcel.writeFloat(f10);
        uk.c.c0(parcel, 21, this.zzt, false);
        long j = this.zzu;
        uk.c.k0(parcel, 25, 8);
        parcel.writeLong(j);
        uk.c.c0(parcel, 26, this.zzv, false);
        uk.c.e0(parcel, 27, this.zzw);
        uk.c.c0(parcel, 28, this.zzx, false);
        uk.c.b0(parcel, 29, this.zzy, i10, false);
        uk.c.e0(parcel, 30, this.zzz);
        long j4 = this.zzA;
        uk.c.k0(parcel, 31, 8);
        parcel.writeLong(j4);
        uk.c.c0(parcel, 33, this.zzB, false);
        float f11 = this.zzC;
        uk.c.k0(parcel, 34, 4);
        parcel.writeFloat(f11);
        int i15 = this.zzD;
        uk.c.k0(parcel, 35, 4);
        parcel.writeInt(i15);
        int i16 = this.zzE;
        uk.c.k0(parcel, 36, 4);
        parcel.writeInt(i16);
        boolean z10 = this.zzF;
        uk.c.k0(parcel, 37, 4);
        parcel.writeInt(z10 ? 1 : 0);
        uk.c.c0(parcel, 39, this.zzG, false);
        boolean z11 = this.zzH;
        uk.c.k0(parcel, 40, 4);
        parcel.writeInt(z11 ? 1 : 0);
        uk.c.c0(parcel, 41, this.zzI, false);
        boolean z12 = this.zzJ;
        uk.c.k0(parcel, 42, 4);
        parcel.writeInt(z12 ? 1 : 0);
        int i17 = this.zzK;
        uk.c.k0(parcel, 43, 4);
        parcel.writeInt(i17);
        uk.c.U(parcel, 44, this.zzL, false);
        uk.c.c0(parcel, 45, this.zzM, false);
        uk.c.b0(parcel, 46, this.zzN, i10, false);
        boolean z13 = this.zzO;
        uk.c.k0(parcel, 47, 4);
        parcel.writeInt(z13 ? 1 : 0);
        uk.c.U(parcel, 48, this.zzP, false);
        uk.c.c0(parcel, 49, this.zzQ, false);
        uk.c.c0(parcel, 50, this.zzR, false);
        uk.c.c0(parcel, 51, this.zzS, false);
        boolean z14 = this.zzT;
        uk.c.k0(parcel, 52, 4);
        parcel.writeInt(z14 ? 1 : 0);
        List list = this.zzU;
        if (list != null) {
            int iH02 = uk.c.h0(53, parcel);
            int size = list.size();
            parcel.writeInt(size);
            for (int i18 = 0; i18 < size; i18++) {
                parcel.writeInt(((Integer) list.get(i18)).intValue());
            }
            uk.c.j0(iH02, parcel);
        }
        uk.c.c0(parcel, 54, this.zzV, false);
        uk.c.e0(parcel, 55, this.zzW);
        int i19 = this.zzX;
        uk.c.k0(parcel, 56, 4);
        parcel.writeInt(i19);
        boolean z15 = this.zzY;
        uk.c.k0(parcel, 57, 4);
        parcel.writeInt(z15 ? 1 : 0);
        boolean z16 = this.zzZ;
        uk.c.k0(parcel, 58, 4);
        parcel.writeInt(z16 ? 1 : 0);
        boolean z17 = this.zzaa;
        uk.c.k0(parcel, 59, 4);
        parcel.writeInt(z17 ? 1 : 0);
        uk.c.e0(parcel, 60, this.zzab);
        uk.c.c0(parcel, 61, this.zzac, false);
        uk.c.b0(parcel, 63, this.zzad, i10, false);
        uk.c.c0(parcel, 64, this.zzae, false);
        uk.c.U(parcel, 65, this.zzaf, false);
        uk.c.j0(iH0, parcel);
    }
}
